// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"context"
	"time"
)

type Querier interface {
	ActivateUser(ctx context.Context, id int64) error
	AdvancedBookSearch(ctx context.Context, arg AdvancedBookSearchParams) ([]*AdvancedBookSearchRow, error)
	AdvancedSearchBooks(ctx context.Context, arg AdvancedSearchBooksParams) ([]*AdvancedSearchBooksRow, error)
	CalculateOverdueFine(ctx context.Context, arg CalculateOverdueFineParams) (*CalculateOverdueFineRow, error)
	CancelReservation(ctx context.Context, reservationID int64) error
	CheckLoanEligibility(ctx context.Context, arg CheckLoanEligibilityParams) (*CheckLoanEligibilityRow, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (*Book, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*BookCategory, error)
	CreateDailyStatistics(ctx context.Context) error
	CreateFine(ctx context.Context, arg CreateFineParams) (*Fine, error)
	CreateLibrarian(ctx context.Context, arg CreateLibrarianParams) (*Librarian, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (*LoanHistory, error)
	CreateOperationLog(ctx context.Context, arg CreateOperationLogParams) error
	CreateReader(ctx context.Context, arg CreateReaderParams) (*Reader, error)
	CreateRenewal(ctx context.Context, arg CreateRenewalParams) error
	CreateRenewalRecord(ctx context.Context, arg CreateRenewalRecordParams) (*Renewal, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (*Reservation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeactivateLibrarian(ctx context.Context, librarianID int64) error
	DeactivateUser(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	FulfillReservation(ctx context.Context, reservationID int64) error
	GetActiveLoansByBook(ctx context.Context, bookID int) ([]*GetActiveLoansByBookRow, error)
	GetActiveReaders(ctx context.Context, resultLimit int32) ([]*GetActiveReadersRow, error)
	GetAllCategories(ctx context.Context) ([]*BookCategory, error)
	GetAllHalls(ctx context.Context) ([]*GetAllHallsRow, error)
	GetAllLibrarians(ctx context.Context) ([]*Librarian, error)
	GetAllReaders(ctx context.Context, arg GetAllReadersParams) ([]*GetAllReadersRow, error)
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]*GetAllUsersRow, error)
	GetAvailableBooks(ctx context.Context, resultLimit int32) ([]*GetAvailableBooksRow, error)
	GetBookByCode(ctx context.Context, bookCode string) (*GetBookByCodeRow, error)
	GetBookByID(ctx context.Context, bookID int64) (*GetBookByIDRow, error)
	GetBookQueue(ctx context.Context, bookID int) ([]*GetBookQueueRow, error)
	GetBooksByAuthorInHall(ctx context.Context, arg GetBooksByAuthorInHallParams) (*GetBooksByAuthorInHallRow, error)
	GetBooksDueToday(ctx context.Context) ([]*GetBooksDueTodayRow, error)
	GetBooksWithSingleCopy(ctx context.Context) ([]*GetBooksWithSingleCopyRow, error)
	GetCategoryStatistics(ctx context.Context) ([]*GetCategoryStatisticsRow, error)
	GetDebtorReaders(ctx context.Context) ([]*GetDebtorReadersRow, error)
	GetExpiredReservations(ctx context.Context) ([]*GetExpiredReservationsRow, error)
	GetHallByID(ctx context.Context, hallID int64) (*Hall, error)
	GetHallStatistics(ctx context.Context) ([]*GetHallStatisticsRow, error)
	GetInventoryReport(ctx context.Context) ([]*GetInventoryReportRow, error)
	GetLibrarianByEmployeeID(ctx context.Context, employeeID string) (*Librarian, error)
	GetLibrarianByID(ctx context.Context, librarianID int64) (*Librarian, error)
	GetLoanByID(ctx context.Context, loanID int64) (*GetLoanByIDRow, error)
	GetLoanStatusStatistics(ctx context.Context, loanDate time.Time) ([]*GetLoanStatusStatisticsRow, error)
	GetMonthlyReport(ctx context.Context) ([]*GetMonthlyReportRow, error)
	GetMostRenewedBooks(ctx context.Context, resultLimit int32) ([]*GetMostRenewedBooksRow, error)
	GetOperationLogs(ctx context.Context, arg GetOperationLogsParams) ([]*GetOperationLogsRow, error)
	GetOverdueBooks(ctx context.Context, resultLimit int32) ([]*GetOverdueBooksRow, error)
	GetPopularBooks(ctx context.Context, resultLimit int32) ([]*GetPopularBooksRow, error)
	GetReaderByID(ctx context.Context, readerID int64) (*GetReaderByIDRow, error)
	GetReaderByTicket(ctx context.Context, ticketNumber string) (*GetReaderByTicketRow, error)
	GetReaderCurrentLoans(ctx context.Context, readerID int) ([]*GetReaderCurrentLoansRow, error)
	GetReaderFavoriteCategories(ctx context.Context, readerID int) ([]*GetReaderFavoriteCategoriesRow, error)
	GetReaderFines(ctx context.Context, readerID int) ([]*GetReaderFinesRow, error)
	GetReaderLoanHistory(ctx context.Context, arg GetReaderLoanHistoryParams) ([]*GetReaderLoanHistoryRow, error)
	GetReaderReservations(ctx context.Context, readerID int) ([]*GetReaderReservationsRow, error)
	GetReaderStatistics(ctx context.Context, readerID int64) (*GetReaderStatisticsRow, error)
	GetReadersCount(ctx context.Context) (int64, error)
	GetRecentOperations(ctx context.Context, resultLimit int32) ([]*GetRecentOperationsRow, error)
	GetRenewalsByDate(ctx context.Context, arg GetRenewalsByDateParams) ([]*GetRenewalsByDateRow, error)
	GetRenewalsForLoan(ctx context.Context, loanHistoryID int) ([]*GetRenewalsForLoanRow, error)
	GetTopRatedBooks(ctx context.Context, resultLimit int32) ([]*GetTopRatedBooksRow, error)
	GetUnpaidFines(ctx context.Context) ([]*GetUnpaidFinesRow, error)
	GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error)
	GetUsersByRole(ctx context.Context, role string) ([]*GetUsersByRoleRow, error)
	GetYearlyReportByCategory(ctx context.Context) ([]*GetYearlyReportByCategoryRow, error)
	GlobalSearch(ctx context.Context, searchTerm string) ([]*GlobalSearchRow, error)
	MarkLoanAsLost(ctx context.Context, id int64) error
	PayFine(ctx context.Context, fineID int64) error
	RenewLoan(ctx context.Context, loanID int64) error
	ReturnBook(ctx context.Context, arg ReturnBookParams) error
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]*SearchBooksRow, error)
	SearchReadersByName(ctx context.Context, arg SearchReadersByNameParams) ([]*SearchReadersByNameRow, error)
	UpdateBookAvailability(ctx context.Context, arg UpdateBookAvailabilityParams) error
	UpdateBookCopies(ctx context.Context, arg UpdateBookCopiesParams) error
	UpdateHallOccupancy(ctx context.Context, hallID int) error
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdateLibrarian(ctx context.Context, arg UpdateLibrarianParams) (*Librarian, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateReader(ctx context.Context, arg UpdateReaderParams) (*Reader, error)
	UpdateReaderDebt(ctx context.Context, readerID int64) error
	UpdateReaderStatus(ctx context.Context, arg UpdateReaderStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*UpdateUserRow, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	WaiveFine(ctx context.Context, fineID int64) error
	WriteOffBook(ctx context.Context, bookID int64) error
}

var _ Querier = (*Queries)(nil)
